# Generated by Django 6.0.4 on 2026-05-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched_bank', 'Unmatched (Bank)'), ('unmatched_ledger', 'Unmatched (Ledger)')], max_length=20)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('date_difference', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recon_result', to='ingestion.banktransaction')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recon_result', to='ingestion.internalledgerentry')),
            ],
            options={
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['status'], name='reconciliat_status_96ed52_idx')],
            },
        ),
    ]
