# Generated by Django 6.0.4 on 2026-05-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('bank', 'Bank'), ('internal', 'Internal')], max_length=10)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=6)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ingestion.banktransaction')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ingestion.internalledgerentry')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='ledger_norm_date_903507_idx'), models.Index(fields=['category'], name='ledger_norm_categor_240c19_idx'), models.Index(fields=['reconciliation_status'], name='ledger_norm_reconci_4e3fe8_idx'), models.Index(fields=['txn_type'], name='ledger_norm_txn_typ_5b7b77_idx')],
            },
        ),
    ]
