# Generated by Django 6.0.4 on 2026-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('bank', 'Bank Statement'), ('ledger', 'Internal Ledger')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_inserted', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='ingestion_b_date_3da096_idx'), models.Index(fields=['amount'], name='ingestion_b_amount_1a3a8a_idx'), models.Index(fields=['txn_type'], name='ingestion_b_txn_typ_9337cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='ingestion_i_date_fe9603_idx'), models.Index(fields=['amount'], name='ingestion_i_amount_d5bcdc_idx'), models.Index(fields=['category'], name='ingestion_i_categor_1a169e_idx')],
            },
        ),
    ]
